/* Data-driven catalog: 20 repeatable camp missions. */
[
    createHashMapFromArray [["id","recruit_volunteers"],["title","Набор добровольцев"],["description","Проведите агитацию в ближайшей деревне."],["category","ЛЮДСКИЕ РЕСУРСЫ"],["manpower",12],["money",0],["eliteGear",0],["economyDamage",0]],
    createHashMapFromArray [["id","escort_recruits"],["title","Сопровождение новобранцев"],["description","Доставьте группу добровольцев в лагерь."],["category","ЛЮДСКИЕ РЕСУРСЫ"],["manpower",18],["money",0],["eliteGear",0],["economyDamage",0]],
    createHashMapFromArray [["id","rescue_prisoners"],["title","Освобождение пленных"],["description","Найдите и выведите пленных из вражеского охранения."],["category","ЛЮДСКИЕ РЕСУРСЫ"],["manpower",15],["money",200],["eliteGear",0],["economyDamage",0]],
    createHashMapFromArray [["id","medevac"],["title","Эвакуация раненых"],["description","Заберите раненых бойцов с линии фронта."],["category","ЛЮДСКИЕ РЕСУРСЫ"],["manpower",10],["money",150],["eliteGear",0],["economyDamage",0]],
    createHashMapFromArray [["id","payroll_raid"],["title","Рейд на кассу гарнизона"],["description","Перехватите деньги противника без потерь среди гражданских."],["category","ДЕНЬГИ"],["manpower",0],["money",900],["eliteGear",0],["economyDamage",4]],
    createHashMapFromArray [["id","smuggler_debt"],["title","Долг контрабандиста"],["description","Верните груз и получите оплату за риск."],["category","ДЕНЬГИ"],["manpower",0],["money",650],["eliteGear",0],["economyDamage",2]],
    createHashMapFromArray [["id","bank_sabotage"],["title","Саботаж военной кассы"],["description","Выведите из строя узел снабжения финансового управления."],["category","ЭКОНОМИКА"],["manpower",0],["money",300],["eliteGear",0],["economyDamage",12]],
    createHashMapFromArray [["id","fuel_depot"],["title","Удар по нефтебазе"],["description","Повредите запас топлива противника и отойдите до тревоги."],["category","ЭКОНОМИКА"],["manpower",0],["money",400],["eliteGear",0],["economyDamage",15]],
    createHashMapFromArray [["id","rail_sabotage"],["title","Разрыв железной дороги"],["description","Остановите военный состав и сорвите перевозку ресурсов."],["category","ЭКОНОМИКА"],["manpower",0],["money",350],["eliteGear",0],["economyDamage",10]],
    createHashMapFromArray [["id","factory_strike"],["title","Сбой на военном заводе"],["description","Выведите из строя оборудование в промышленной зоне."],["category","ЭКОНОМИКА"],["manpower",0],["money",500],["eliteGear",0],["economyDamage",18]],
    createHashMapFromArray [["id","armory_capture"],["title","Захват оружейной"],["description","Захватите склад и вынесите редкое снаряжение."],["category","ЭЛИТНАЯ ЭКИПИРОВКА"],["manpower",0],["money",250],["eliteGear",2],["economyDamage",3]],
    createHashMapFromArray [["id","officer_hunt"],["title","Охота на офицера"],["description","Выследите офицера связи и заберите его комплект."],["category","ЭЛИТНАЯ ЭКИПИРОВКА"],["manpower",0],["money",300],["eliteGear",1],["economyDamage",5]],
    createHashMapFromArray [["id","night_drop"],["title","Ночной сброс"],["description","Примите тайный груз и доставьте его в лагерь."],["category","ЭЛИТНАЯ ЭКИПИРОВКА"],["manpower",0],["money",200],["eliteGear",3],["economyDamage",0]],
    createHashMapFromArray [["id","sniper_cache"],["title","Тайник наблюдателя"],["description","Найдите тайник разведчика на господствующей высоте."],["category","ЭЛИТНАЯ ЭКИПИРОВКА"],["manpower",0],["money",150],["eliteGear",1],["economyDamage",0]],
    createHashMapFromArray [["id","radio_intercept"],["title","Перехват радиосети"],["description","Захватите оборудование и получите координаты противника."],["category","РАЗВЕДКА"],["manpower",0],["money",250],["eliteGear",1],["economyDamage",6]],
    createHashMapFromArray [["id","map_recovery"],["title","Возврат карт"],["description","Верните украденные карты района из патрульной машины."],["category","РАЗВЕДКА"],["manpower",0],["money",180],["eliteGear",0],["economyDamage",4]],
    createHashMapFromArray [["id","checkpoint_disruption"],["title","Срыв работы КПП"],["description","Ослабьте контроль на дороге и не поднимайте тревогу."],["category","ПАРТИЗАНСКИЙ УДАР"],["manpower",0],["money",250],["eliteGear",0],["economyDamage",8]],
    createHashMapFromArray [["id","supply_ambush"],["title","Засада на снабжение"],["description","Перехватите колонну снабжения и уничтожьте груз."],["category","ПАРТИЗАНСКИЙ УДАР"],["manpower",0],["money",450],["eliteGear",0],["economyDamage",14]],
    createHashMapFromArray [["id","propaganda"],["title","Листовки сопротивления"],["description","Распространите обращение и поднимите поддержку населения."],["category","ПОДДЕРЖКА"],["manpower",8],["money",100],["eliteGear",0],["economyDamage",5]],
    createHashMapFromArray [["id","resupply_camp"],["title","Пополнение лагеря"],["description","Доставьте медикаменты и боеприпасы в передовой лагерь."],["category","ЛОГИСТИКА"],["manpower",4],["money",300],["eliteGear",1],["economyDamage",0]]
]
