if (!hasInterface) exitWith {false};
params ["_campId"];
private _sites = missionNamespace getVariable ["LW_ambientSites", createHashMap];
private _site = _sites getOrDefault [_campId, createHashMap];
private _position = _site getOrDefault ["position", []];
if (_position isEqualTo [] || {player distance2D _position > 80}) exitWith {hint "Вы должны находиться рядом с лагерем."; false};
private _display = (findDisplay 46) createDisplay "RscDisplayEmpty";
private _bg = _display ctrlCreate ["RscText", 5200];
_bg ctrlSetPosition [0.10, 0.10, 0.80, 0.80];
_bg ctrlSetBackgroundColor [0.02, 0.02, 0.02, 0.94];
_bg ctrlCommit 0;
private _title = _display ctrlCreate ["RscText", 5201];
_title ctrlSetPosition [0.13, 0.13, 0.72, 0.06];
_title ctrlSetText format ["ЛАГЕРЬ: %1 — ЗАДАЧИ СОПРОТИВЛЕНИЯ", _campId];
_title ctrlSetTextColor [1, 0.8, 0.25, 1];
_title ctrlCommit 0;
private _body = _display ctrlCreate ["RscStructuredText", 5202];
_body ctrlSetPosition [0.13, 0.22, 0.72, 0.42];
_body ctrlSetStructuredText parseText "<t size='1.05'>Получайте случайные задачи для пополнения людских ресурсов, денег и элитного снаряжения. Некоторые задания наносят ущерб экономике противника.</t><br/><br/>Категории: люди, деньги, разведка, логистика, поддержка, партизанские удары, экономика.";
_body ctrlCommit 0;
private _button = _display ctrlCreate ["RscButton", 5203];
_button ctrlSetPosition [0.13, 0.69, 0.32, 0.07];
_button ctrlSetText "ПОЛУЧИТЬ СЛУЧАЙНУЮ ЗАДАЧУ";
_button ctrlAddEventHandler ["ButtonClick", format ["[player, '%1'] remoteExecCall ['LW_fnc_requestCampMission', 2];", _campId]];
_button ctrlCommit 0;
private _close = _display ctrlCreate ["RscButton", 5204];
_close ctrlSetPosition [0.53, 0.69, 0.32, 0.07];
_close ctrlSetText "ЗАКРЫТЬ";
_close ctrlAddEventHandler ["ButtonClick", "(ctrlParent (_this select 0)) closeDisplay 2;"];
_close ctrlCommit 0;
true
